server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crud}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:3091}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
